"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
class WAMG_Constants {
    constructor() {
    }
}
WAMG_Constants.timezones = [
    // {"abbr": "ACDT", "name": "Australian Central Daylight Time", "offset": "+10:30"},
    // {"abbr": "ACST", "name": "Australian Central Standard Time", "offset": "+9:30"},
    { "abbr": "ADT", "name": "Atlantic Daylight Time", "offset": "-3" },
    { "abbr": "AEDT", "name": "Australian Eastern Daylight Time", "offset": "+11" },
    { "abbr": "AEST", "name": "Australian Eastern Standard Time", "offset": "+10" },
    // {"abbr": "AFT", "name": "Afghanistan Time", "offset": "+4:30"},
    { "abbr": "AKDT", "name": "Alaska Daylight Time", "offset": "-8" },
    { "abbr": "AKST", "name": "Alaska Standard Time", "offset": "-9" },
    { "abbr": "AMST", "name": "Armenia Summer Time", "offset": "+5" },
    { "abbr": "AMT", "name": "Armenia Time", "offset": "+4" },
    { "abbr": "ART", "name": "Argentina Time", "offset": "-3" },
    { "abbr": "AST", "name": "Arab Standard Time (Kuwait, Riyadh)", "offset": "+3" },
    { "abbr": "AST", "name": "Arabian Standard Time (Abu Dhabi, Muscat)", "offset": "+4" },
    // {"abbr": "AST", "name": "Arabic Standard Time (Baghdad)", "offset": "+3"},
    { "abbr": "AST", "name": "Atlantic Standard Time", "offset": "-4" },
    { "abbr": "AWDT", "name": "Australian Western Daylight Time", "offset": "+9" },
    { "abbr": "AWST", "name": "Australian Western Standard Time", "offset": "+8" },
    { "abbr": "AZOST", "name": "Azores Standard Time", "offset": "-1" },
    { "abbr": "AZT", "name": "Azerbaijan Time", "offset": "+4" },
    { "abbr": "BDT", "name": "Brunei Time", "offset": "+8" },
    { "abbr": "BIOT", "name": "British Indian Ocean Time", "offset": "+6" },
    { "abbr": "BIT", "name": "Baker Island Time", "offset": "-12" },
    { "abbr": "BOT", "name": "Bolivia Time", "offset": "-4" },
    { "abbr": "BRT", "name": "Brasilia Time", "offset": "-3" },
    { "abbr": "BST", "name": "Bangladesh Standard Time", "offset": "+6" },
    { "abbr": "BST", "name": "British Summer Time", "offset": "+1" },
    { "abbr": "BTT", "name": "Bhutan Time", "offset": "+6" },
    { "abbr": "CAT", "name": "Central Africa Time", "offset": "+2" },
    // {"abbr": "CCT", "name": "Cocos Islands Time", "offset": "+6:30"},
    { "abbr": "CDT", "name": "Central Daylight Time (North America)", "offset": "-5" },
    { "abbr": "CEDT", "name": "Central European Daylight Time", "offset": "+2" },
    { "abbr": "CEST", "name": "Central European Summer Time", "offset": "+2" },
    { "abbr": "CET", "name": "Central European Time", "offset": "+1" },
    // {"abbr": "CHADT", "name": "Chatham Daylight Time", "offset": "+13:45"},
    // {"abbr": "CHAST", "name": "Chatham Standard Time", "offset": "+12:45"},
    { "abbr": "CIST", "name": "Clipperton Island Standard Time", "offset": "-8" },
    { "abbr": "CKT", "name": "Cook Island Time", "offset": "-10" },
    { "abbr": "CLST", "name": "Chile Summer Time", "offset": "-3" },
    { "abbr": "CLT", "name": "Chile Standard Time", "offset": "-4" },
    { "abbr": "COST", "name": "Colombia Summer Time", "offset": "-4" },
    { "abbr": "COT", "name": "Colombia Time", "offset": "-5" },
    { "abbr": "CST", "name": "Central Standard Time (North America)", "offset": "-6" },
    { "abbr": "CST", "name": "China Standard Time", "offset": "+8" },
    // {"abbr": "CST", "name": "Central Standard Time (Australia)", "offset": "+9:30"},
    { "abbr": "CT", "name": "China Time", "offset": "+8" },
    { "abbr": "CVT", "name": "Cape Verde Time", "offset": "-1" },
    { "abbr": "CXT", "name": "Christmas Island Time", "offset": "+7" },
    { "abbr": "CHST", "name": "Chamorro Standard Time", "offset": "+10" },
    { "abbr": "DFT", "name": "AIX specific equivalent of Central European Time", "offset": "+1" },
    { "abbr": "EAST", "name": "Easter Island Standard Time", "offset": "-6" },
    { "abbr": "EAT", "name": "East Africa Time", "offset": "+3" },
    { "abbr": "ECT", "name": "Eastern Caribbean Time", "offset": "-4" },
    { "abbr": "ECT", "name": "Ecuador Time", "offset": "-5" },
    { "abbr": "EDT", "name": "Eastern Daylight Time (North America)", "offset": "-4" },
    { "abbr": "EEDT", "name": "Eastern European Daylight Time", "offset": "+3" },
    { "abbr": "EEST", "name": "Eastern European Summer Time", "offset": "+3" },
    { "abbr": "EET", "name": "Eastern European Time", "offset": "+2" },
    { "abbr": "EST", "name": "Eastern Standard Time (North America)", "offset": "-5" },
    { "abbr": "FJT", "name": "Fiji Time", "offset": "+12" },
    { "abbr": "FKST", "name": "Falkland Islands Summer Time", "offset": "-3" },
    { "abbr": "FKT", "name": "Falkland Islands Time", "offset": "-4" },
    { "abbr": "GALT", "name": "Galapagos Time", "offset": "-6" },
    { "abbr": "GET", "name": "Georgia Standard Time", "offset": "+4" },
    { "abbr": "GFT", "name": "French Guiana Time", "offset": "-3" },
    { "abbr": "GILT", "name": "Gilbert Island Time", "offset": "+12" },
    { "abbr": "GIT", "name": "Gambier Island Time", "offset": "-9" },
    { "abbr": "GMT", "name": "Greenwich Mean Time", "offset": "0" },
    { "abbr": "GST", "name": "South Georgia and the South Sandwich Island", "offset": "-2" },
    { "abbr": "GST", "name": "Gulf Standard Time", "offset": "+4" },
    { "abbr": "GYT", "name": "Guyana Time", "offset": "-4" },
    { "abbr": "HADT", "name": "Hawaii-Aleutian Daylight Time", "offset": "-9" },
    { "abbr": "HAEC", "name": "Heure Avancée d'Europe Centrale French for CEST", "offset": "+2" },
    { "abbr": "HAST", "name": "Hawaii-Aleutian Standard Time", "offset": "-10" },
    { "abbr": "HKT", "name": "Hong Kong Time", "offset": "+8" },
    { "abbr": "HMT", "name": "Heard and McDonald Islands Time", "offset": "+5" },
    { "abbr": "HST", "name": "Hawaii Standard Time", "offset": "-10" },
    { "abbr": "ICT", "name": "Indochina Time", "offset": "+7" },
    { "abbr": "IDT", "name": "Israeli Daylight Time", "offset": "+3" },
    { "abbr": "IRKT", "name": "Irkutsk Time", "offset": "+8" },
    // {"abbr": "IRST", "name": "Iran Standard Time", "offset": "+3:30"},
    // {"abbr": "IST", "name": "Indian Standard Time", "offset": "+5:30"},
    { "abbr": "IST", "name": "Irish Summer Time", "offset": "+1" },
    { "abbr": "IST", "name": "Israel Standard Time", "offset": "+2" },
    { "abbr": "JST", "name": "Japan Standard Time", "offset": "+9" },
    { "abbr": "KRAT", "name": "Krasnoyarsk Time", "offset": "+7" },
    { "abbr": "KST", "name": "Korea Standard Time", "offset": "+9" },
    // {"abbr": "LHST", "name": "Lord Howe Standard Time", "offset": "+10:30"},
    { "abbr": "LINT", "name": "Line Islands Time", "offset": "+14" },
    { "abbr": "MAGT", "name": "Magadan Time", "offset": "+11" },
    { "abbr": "MDT", "name": "Mountain Daylight Time (North America)", "offset": "-6" },
    { "abbr": "MET", "name": "Middle European Time (Same as CET)", "offset": "+1" },
    { "abbr": "MEST", "name": "Middle European Saving Time (Same as CEST)", "offset": "+2" },
    // {"abbr": "MIT", "name": "Marquesas Islands Time", "offset": "-9:30"},
    { "abbr": "MSD", "name": "Moscow Summer Time", "offset": "+4" },
    { "abbr": "MSK", "name": "Moscow Standard Time", "offset": "+3" },
    { "abbr": "MST", "name": "Malaysian Standard Time", "offset": "+8" },
    { "abbr": "MST", "name": "Mountain Standard Time (North America)", "offset": "-7" },
    // {"abbr": "MST", "name": "Myanmar Standard Time", "offset": "+6:30"},
    { "abbr": "MUT", "name": "Mauritius Time", "offset": "+4" },
    { "abbr": "MYT", "name": "Malaysia Time", "offset": "+8" },
    // {"abbr": "NDT", "name": "Newfoundland Daylight Time", "offset": "-2:30"},
    // {"abbr": "NFT", "name": "Norfolk Time", "offset": "+11:30"},
    // {"abbr": "NPT", "name": "Nepal Time", "offset": "+5:45"},
    // {"abbr": "NST", "name": "Newfoundland Standard Time", "offset": "-3:30"},
    // {"abbr": "NT", "name": "Newfoundland Time", "offset": "-3:30"},
    { "abbr": "NZDT", "name": "New Zealand Daylight Time", "offset": "+13" },
    { "abbr": "NZST", "name": "New Zealand Standard Time", "offset": "+12" },
    { "abbr": "OMST", "name": "Omsk Time", "offset": "+6" },
    { "abbr": "PDT", "name": "Pacific Daylight Time (North America)", "offset": "-7" },
    { "abbr": "PETT", "name": "Kamchatka Time", "offset": "+12" },
    { "abbr": "PHOT", "name": "Phoenix Island Time", "offset": "+13" },
    { "abbr": "PKT", "name": "Pakistan Standard Time", "offset": "+5" },
    { "abbr": "PST", "name": "Pacific Standard Time (North America)", "offset": "-8" },
    { "abbr": "PST", "name": "Philippine Standard Time", "offset": "+8" },
    { "abbr": "RET", "name": "Réunion Time", "offset": "+4" },
    { "abbr": "SAMT", "name": "Samara Time", "offset": "+4" },
    { "abbr": "SAST", "name": "South African Standard Time", "offset": "+2" },
    { "abbr": "SBT", "name": "Solomon Islands Time", "offset": "+11" },
    { "abbr": "SCT", "name": "Seychelles Time", "offset": "+4" },
    { "abbr": "SGT", "name": "Singapore Time", "offset": "+8" },
    // {"abbr": "SLT", "name": "Sri Lanka Time", "offset": "+5:30"},
    { "abbr": "SST", "name": "Samoa Standard Time", "offset": "-11" },
    { "abbr": "SST", "name": "Singapore Standard Time", "offset": "+8" },
    { "abbr": "TAHT", "name": "Tahiti Time", "offset": "-10" },
    { "abbr": "THA", "name": "Thailand Standard Time", "offset": "+7" },
    { "abbr": "UTC", "name": "Coordinated Universal Time", "offset": "0" },
    { "abbr": "UYST", "name": "Uruguay Summer Time", "offset": "-2" },
    { "abbr": "UYT", "name": "Uruguay Standard Time", "offset": "-3" },
    // {"abbr": "VET", "name": "Venezuelan Standard Time", "offset": "-4:30"},
    { "abbr": "VLAT", "name": "Vladivostok Time", "offset": "+10" },
    { "abbr": "WAT", "name": "West Africa Time", "offset": "+1" },
    { "abbr": "WEDT", "name": "Western European Daylight Time", "offset": "+1" },
    { "abbr": "WEST", "name": "Western European Summer Time", "offset": "+1" },
    { "abbr": "WET", "name": "Western European Time", "offset": "0" },
    { "abbr": "WST", "name": "Western Standard Time", "offset": "+8" },
    { "abbr": "YAKT", "name": "Yakutsk Time", "offset": "+9" },
    { "abbr": "YEKT", "name": "Yekaterinburg Time", "offset": "+5" }
];
exports.WAMG_Constants = WAMG_Constants;
//# sourceMappingURL=Constants.js.map